INSERT INTO COUNTRIES (NAME, CODE) VALUES ('Turkey', 'TR');
INSERT INTO HOLIDAY_TYPES (CODE) VALUES ('OFFICIAL');
INSERT INTO HOLIDAY_TYPE_TRANSLATIONS (HOLIDAY_TYPE_ID, LANGUAGE_CODE, NAME)
    SELECT ID, 'tr', 'Resmi Tatil' FROM HOLIDAY_TYPES WHERE CODE='OFFICIAL';
INSERT INTO TARGET_GROUPS (CODE) VALUES ('GEN');
INSERT INTO TARGET_GROUP_TRANSLATIONS (TARGET_GROUP_ID, LANGUAGE_CODE, NAME)
    SELECT ID, 'tr', 'Genel' FROM TARGET_GROUPS WHERE CODE='GEN';
INSERT INTO HOLIDAYS (CODE, COUNTRY_ID, HOLIDAY_TYPE_ID, START_DATE, END_DATE, IS_NATIONAL, IS_VARIABLE)
    VALUES ('BAYRAM', (SELECT ID FROM COUNTRIES WHERE CODE='TR'),
            (SELECT ID FROM HOLIDAY_TYPES WHERE CODE='OFFICIAL'),
            DATE '2025-10-29', DATE '2025-10-29', 1, 0);
INSERT INTO HOLIDAY_DESCRIPTIONS (HOLIDAY_ID, LANGUAGE_CODE, NAME, DESCRIPTION)
        SELECT h.ID, 'tr', 'Cumhuriyet Bayramı', 'Turkey national day' FROM HOLIDAYS h WHERE h.CODE='BAYRAM';
INSERT INTO HOLIDAY_TARGET_GROUPS (HOLIDAY_ID, TARGET_GROUP_ID)
    SELECT h.ID, tg.ID FROM HOLIDAYS h, TARGET_GROUPS tg WHERE h.CODE='BAYRAM' AND tg.CODE='GEN';
COMMIT;
